### PR TITLE
Fix Seek() to SORTED_DELETE_RECORD, and reorganize tests

### PR DESCRIPTION
**Pull request by ZiyanShi**

### CODE REVIEW

**Comment by JiayuZzz** [comment]
File changes in tests are ambiguous, could you please briefly describe what have you modified?

**Comment by ZiyanShi** [comment]
Add counter to TestBasicSortedOperations to check that the total number of existing entries matches the operations. The check is done by ops2 so that all modifies to the global_skiplist is done by all threads.
Add TestSeek2 to assure that Seek() won't move iterator to a SORTED_DELETE_RECORD.
Reordered all test cases so that they become more organized. Someone has to do it before test.cpp becomes too large.
Four new DATA_ENTRY_TYPE comes from another working directory. I forgot to unstage the files.

**Comment by KVKIT** [comment]
Are the added unit tests related to the issue ? If not, please consider to add two PRs.

In addition, for unit tests, it's better that the test case name can express what it intends to test. (Let single unit test just test one thing).

**Comment by ZiyanShi** [comment]
One unit test is added. It's named TestSeek2 because TestSeek is already used.
TestSeek2 is separated from TestBasicSortedOperations. A counter is added to TestBasicSortedOperations to ensure the number of entries is consistent with operations done by all threads.
All test cases are reordered according to their functionality.

**Review by JiayuZzz — APPROVED** [review]
LGTM

**Comment by JiayuZzz** [comment]
> One unit test is added. It's named TestSeek2 because TestSeek is already used.
> TestSeek2 is separated from TestBasicSortedOperations. A counter is added to TestBasicSortedOperations to ensure the number of entries is consistent with operations done by all threads.
> All test cases are reordered according to their functionality.

Can you please merge TestSeek2 into TestSeek?

**Pull request merged**
